### ISSUE TITLE
Calculation of pearson correlation between genes in each cell-line

### ISSUE THREAD

**Issue by songsong0425** [kunjiefan/MVGCNiSL#1]
Greetings, thank you for your effort in developing the model.
I have a question about the co-expression and co-essentiality network.

Generally, at least three values were needed to calculate the Pearson correlation between samples.
But when I read the paper, I think that there was only one value per gene in the cell lines (K562 and Jurkat).
How did you calculate the Pearson correlation between genes with gene expression and essentiality score?

I look forward to your reply.

**Comment by kunjiefan** [comment]
Hi, Thanks for your interest in this work.

Like we mentioned in the paper, the co-expression and co-essentiality network is based on the expression/essentiality profiles across all cell lines in CCLE. They are not specific to K562 or Jurkat cell line.

Hope this will solve your question.

Best,
Kunjie

**Comment by songsong0425** [comment]
Thank you for your reply. I totally understand the process and a question is resolved. :)
